In [2]:
import pandas as pd
import numpy as np

In [3]:
be_data=pd.read_csv('BE_data.csv')

In [4]:
be_data.head()

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,DS,*****,*****
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.10183469
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.10183469
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.01597325
4,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,SC,-----,-----

In [11]:
be_data

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,DS,*****,*****
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.10183469
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.10183469
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.01597325
4,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,SC,<NA>,<NA>
...,...,...,...,...,...,...
5581,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,EWS,<NA>,<NA>
5582,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.95132098
5583,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,SC,<NA>,<NA>
5584,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,SEBC,<NA>,<NA>
5585,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.2351673

In [13]:
be_data=pd.read_csv('BE_data_na.csv')

In [18]:
be_data.replace(' ',pd.NA,inplace=True)

In [19]:
be_data.dropna()

,Unnamed: 0,CollegeName,Location,Course,Category,Rank,MerirMarks
1,1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.10183469
2,2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.10183469
3,3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.01597325
6,6,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,TFW,4015,88.85688166
10,10,A.D.Patel Institute Of Technology,Karamsad,AUTOMOBILE ENGINEERING,Open,VAC,VAC
...,...,...,...,...,...,...,...
5576,5576,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SC,17393,57.11092578
5577,5577,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SEBC,13859,65.62325254
5578,5578,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,TFW,6241,83.64492943
5582,5582,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.95132098
5585,5585,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.2351673

In [24]:
be_data['MerirMarks'] = be_data['MerirMarks'].convert_dtypes().replace('VAC', '0')

# Replace 'VAC' with '40000' in 'rank' column
be_data['Rank'] = be_data['Rank'].convert_dtypes().replace('VAC', '40000')

In [26]:
type(be_data['Rank'][2])

str

In [29]:
be_data.dropna(inplace=True)

In [37]:
be_data.to_csv('BE_data2.csv')

In [32]:
be_data.to_numeric(be_data['Rank'], errors='coerce')

AttributeError: 'DataFrame' object has no attribute 'to_numeric'

In [38]:
be_data=pd.read_csv('BE_data2.csv')

In [40]:
be_data['Rank']=be_data['Rank'].astype(int)

In [43]:
import decimal
be_data.MerirMarks=be_data.MerirMarks.apply(lambda x: decimal.Decimal(x) if x else pd.NA)

In [45]:
be_data.dropna(inplace=True)

In [49]:
be_data.drop('Unnamed: 0.1',axis=1,inplace=True)

In [51]:
be_data.drop('Unnamed: 0',axis=1,inplace=True)

In [55]:
be_data.describe()

               Rank
count   1395.000000
mean   15259.438710
std    10647.697674
min       14.000000
25%     6228.000000
50%    13270.000000
75%    23726.500000
max    34584.000000

In [64]:
be_data.MerirMarks=be_data.MerirMarks.astype(float)

In [65]:
be_data.describe()

               Rank   MerirMarks
count   1395.000000  1395.000000
mean   15259.438710    60.801532
std    10647.697674    27.932356
min       14.000000     0.195797
25%     6228.000000    41.252942
50%    13270.000000    67.090655
75%    23726.500000    83.683487
max    34584.000000    99.883043

In [66]:
be_data.info

<bound method DataFrame.info of                                      CollegeName   Location  \
0              A.D.Patel Institute Of Technology   Karamsad
1              A.D.Patel Institute Of Technology   Karamsad
2              A.D.Patel Institute Of Technology   Karamsad
3              A.D.Patel Institute Of Technology   Karamsad
6              A.D.Patel Institute Of Technology   Karamsad
...                                          ...        ...
1841  Vishwakarma Government Engineering College  Ahmedabad
1842  Vishwakarma Government Engineering College  Ahmedabad
1843  Vishwakarma Government Engineering College  Ahmedabad
1844  Vishwakarma Government Engineering College  Ahmedabad
1845  Vishwakarma Government Engineering College  Ahmedabad

                                        Course Category   Rank  MerirMarks
0     ARTIFICIAL INTELLIGENCE AND DATA SCIENCE      EVS  18200   55.101835
1     ARTIFICIAL INTELLIGENCE AND DATA SCIENCE      EWS  18200   55.101835
2     ARTIFICIAL INTELLIGENCE AND DATA SCIENCE     Open  14510   64.015973
3     ARTIFICIAL INTELLIGENCE AND DATA SCIENCE      TFW   4015   88.856882
6                         COMPUTER ENGINEERING       DS  12154   69.730645
...                                        ...      ...    ...         ...
1841                    MECHANICAL ENGINEERING       SC  17393   57.110926
1842                    MECHANICAL ENGINEERING     SEBC  13859   65.623253
1843                    MECHANICAL ENGINEERING      TFW   6241   83.644929
1844                         POWER ELECTRONICS     Open  32209   16.951321
1845                         POWER ELECTRONICS      TFW  14812   63.235167

[1395 rows x 6 columns]>

In [76]:
be_data.to_csv('BE_final.csv')

In [77]:
be_data

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.101835
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.101835
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.015973
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,TFW,4015,88.856882
6,A.D.Patel Institute Of Technology,Karamsad,COMPUTER ENGINEERING,DS,12154,69.730645
...,...,...,...,...,...,...
1841,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SC,17393,57.110926
1842,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SEBC,13859,65.623253
1843,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,TFW,6241,83.644929
1844,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.951321
1845,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.235167

In [82]:
df=pd.read_csv('BE_final.csv')

In [83]:
df

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.101835
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.101835
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.015973
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,TFW,4015,88.856882
4,A.D.Patel Institute Of Technology,Karamsad,COMPUTER ENGINEERING,DS,12154,69.730645
...,...,...,...,...,...,...
1390,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SC,17393,57.110926
1391,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SEBC,13859,65.623253
1392,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,TFW,6241,83.644929
1393,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.951321
1394,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.235167

In [84]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [85]:
import pickle

In [87]:
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label_encoder, file)

In [88]:
df

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.101835
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.101835
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.015973
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,TFW,4015,88.856882
4,A.D.Patel Institute Of Technology,Karamsad,COMPUTER ENGINEERING,DS,12154,69.730645
...,...,...,...,...,...,...
1390,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SC,17393,57.110926
1391,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,SEBC,13859,65.623253
1392,Vishwakarma Government Engineering College,Ahmedabad,MECHANICAL ENGINEERING,TFW,6241,83.644929
1393,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.951321
1394,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.235167

In [89]:
df.CollegeName=label_encoder.fit_transform(df.CollegeName)
df.Location=label_encoder.fit_transform(df.Location)
df.Course=label_encoder.fit_transform(df.Course)
df.Category=label_encoder.fit_transform(df.Category)

In [90]:
df

      CollegeName  Location  Course  Category   Rank  MerirMarks
0               0        62       3         1  18200   55.101835
1               0        62       3         2  18200   55.101835
2               0        62       3         3  14510   64.015973
3               0        62       3         6   4015   88.856882
4               0        62      14         0  12154   69.730645
...           ...       ...     ...       ...    ...         ...
1390           94        56      52         4  17393   57.110926
1391           94        56      52         5  13859   65.623253
1392           94        56      52         6   6241   83.644929
1393           94        56      60         3  32209   16.951321
1394           94        56      60         6  14812   63.235167

[1395 rows x 6 columns]

In [91]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# Assuming you have a DataFrame named 'data' with features and the target variable (label)
# X contains the features, and y contains the target variable

# Split the data into features (X) and target variable (y)
X = df.drop('CollegeName', axis=1)
y = df['CollegeName']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the Decision Tree Classifier
clf = DecisionTreeClassifier()

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Accuracy: 0.7526881720430108
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.80      1.00      0.89         4
           2       0.50      0.50      0.50         2
           3       1.00      0.67      0.80         3
           4       0.50      0.40      0.44         5
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       1.00      0.83      0.91         6
          12       0.50      1.00      0.67         1
          13       0.00      0.00      0.00         0
          15       1.00      1.00      1.00         3
          16       1.00      1.00      1.00         2
          17       1.00      1.00      1.00         6
          19       0.57      0.80      0.67         5
          20       1.00      1.00      1.00         5
          21       1.00      0.80      0.89         5
          23       1.00      1.00      1.00        12
          24       1.00      1.00      1.00        16
          25       1.00      1.00      1.00         1
          26       1.00      1.00      1.00         3
          27       0.00      0.00      0.00         0
          28       1.00      1.00      1.00         6
          29       1.00      1.00      1.00         8
          30       1.00      0.80      0.89        35
          32       0.00      0.00      0.00         1
          34       1.00      1.00      1.00         2
          35       1.00      1.00      1.00         3
          36       0.33      0.43      0.38         7
          37       0.00      0.00      0.00         2
          41       1.00      1.00      1.00         2
          42       0.59      0.81      0.68        16
          43       0.67      1.00      0.80         2
          44       1.00      1.00      1.00         6
          45       0.67      0.40      0.50        10
          46       1.00      1.00      1.00         1
          50       0.00      0.00      0.00         2
          52       0.75      1.00      0.86         3
          53       1.00      1.00      1.00         3
          54       0.00      0.00      0.00         0
          55       0.88      0.70      0.78        10
          56       0.30      0.38      0.33         8
          57       0.50      0.42      0.45        12
          58       0.00      0.00      0.00         1
          60       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         0
          62       1.00      1.00      1.00         2
          63       1.00      1.00      1.00         3
          64       1.00      0.50      0.67         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         4
          67       1.00      1.00      1.00         1
          68       1.00      1.00      1.00         1
          69       0.50      0.67      0.57         3
          70       0.00      0.00      0.00         1
          72       1.00      1.00      1.00         3
          73       0.75      0.60      0.67         5
          74       0.00      0.00      0.00         3
          77       1.00      0.50      0.67         2
          79       0.00      0.00      0.00         0
          81       0.33      1.00      0.50         1
          82       0.00      0.00      0.00         1
          83       0.50      1.00      0.67         1
          84       1.00      1.00      1.00         1
          85       1.00      1.00      1.00         1
          89       1.00      1.00      1.00         1
          90       0.14      1.00      0.25         1
          92       0.00      0.00      0.00         0
          93       1.00      1.00      1.00         2
          94       1.00      0.93      0.96        14

    accuracy                           0.75       279
   macro avg       0.61      0.63      0.60       279
weighted avg       0.78      0.75      0.76       279

d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [92]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Assuming you have a DataFrame named 'data' with features and the target variable (label)
# X contains the features, and y contains the target variable

# Split the data into features (X) and target variable (y)
X = df.drop('CollegeName', axis=1)
y = df['CollegeName']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the Random Forest Classifier
clf = RandomForestClassifier()

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Accuracy: 0.6881720430107527
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       0.80      1.00      0.89         4
           2       0.50      0.50      0.50         2
           3       1.00      0.67      0.80         3
           4       0.38      0.60      0.46         5
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       0.80      0.67      0.73         6
          12       0.33      1.00      0.50         1
          15       1.00      1.00      1.00         3
          16       0.00      0.00      0.00         2
          17       0.57      0.67      0.62         6
          18       0.00      0.00      0.00         0
          19       0.43      0.60      0.50         5
          20       1.00      1.00      1.00         5
          21       1.00      0.80      0.89         5
          23       0.86      1.00      0.92        12
          24       1.00      1.00      1.00        16
          25       1.00      1.00      1.00         1
          26       1.00      1.00      1.00         3
          27       0.00      0.00      0.00         0
          28       1.00      0.50      0.67         6
          29       0.78      0.88      0.82         8
          30       0.86      0.86      0.86        35
          32       0.00      0.00      0.00         1
          34       0.33      0.50      0.40         2
          35       1.00      1.00      1.00         3
          36       0.38      0.43      0.40         7
          37       0.00      0.00      0.00         2
          41       0.00      0.00      0.00         2
          42       0.59      0.81      0.68        16
          43       0.50      1.00      0.67         2
          44       1.00      0.67      0.80         6
          45       0.71      0.50      0.59        10
          46       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         2
          52       0.67      0.67      0.67         3
          53       1.00      1.00      1.00         3
          55       0.58      0.70      0.64        10
          56       0.44      0.50      0.47         8
          57       0.64      0.58      0.61        12
          58       0.00      0.00      0.00         1
          60       0.00      0.00      0.00         1
          61       0.00      0.00      0.00         0
          62       0.00      0.00      0.00         2
          63       0.75      1.00      0.86         3
          64       1.00      1.00      1.00         2
          65       0.00      0.00      0.00         0
          66       1.00      0.25      0.40         4
          67       0.00      0.00      0.00         1
          68       1.00      1.00      1.00         1
          69       1.00      0.67      0.80         3
          70       0.00      0.00      0.00         1
          72       1.00      0.67      0.80         3
          73       0.43      0.60      0.50         5
          74       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         2
          79       0.00      0.00      0.00         0
          80       0.00      0.00      0.00         0
          81       0.33      1.00      0.50         1
          82       0.00      0.00      0.00         1
          83       0.33      1.00      0.50         1
          84       1.00      1.00      1.00         1
          85       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         0
          89       1.00      1.00      1.00         1
          90       0.25      1.00      0.40         1
          93       0.00      0.00      0.00         2
          94       0.92      0.86      0.89        14

    accuracy                           0.69       279
   macro avg       0.47      0.49      0.46       279
weighted avg       0.69      0.69      0.67       279

d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [94]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Assuming you have a DataFrame named 'data' with features and the target variable (label)
# X contains the features, and y contains the target variable

# Split the data into features (X) and target variable (y)
X = df.drop('CollegeName', axis=1)
y = df['CollegeName']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the Logistic Regression Classifier
clf = LogisticRegression()

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Accuracy: 0.13620071684587814
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         6
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         6
          19       0.00      0.00      0.00         5
          20       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         5
          23       0.00      0.00      0.00        12
          24       0.00      0.00      0.00        16
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         3
          28       0.00      0.00      0.00         6
          29       0.00      0.00      0.00         8
          30       0.12      0.86      0.22        35
          32       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         3
          36       0.00      0.00      0.00         7
          37       0.00      0.00      0.00         2
          41       0.00      0.00      0.00         2
          42       0.21      0.50      0.30        16
          43       0.00      0.00      0.00         2
          44       0.00      0.00      0.00         6
          45       0.00      0.00      0.00        10
          46       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         2
          52       0.00      0.00      0.00         3
          53       0.00      0.00      0.00         3
          55       0.00      0.00      0.00        10
          56       0.00      0.00      0.00         8
          57       0.00      0.00      0.00        12
          58       0.00      0.00      0.00         1
          60       0.00      0.00      0.00         1
          62       0.00      0.00      0.00         2
          63       0.00      0.00      0.00         3
          64       0.00      0.00      0.00         2
          66       0.00      0.00      0.00         4
          67       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         3
          70       0.00      0.00      0.00         1
          72       0.00      0.00      0.00         3
          73       0.00      0.00      0.00         5
          74       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         2
          81       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         1
          84       0.00      0.00      0.00         1
          85       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          93       0.00      0.00      0.00         2
          94       0.00      0.00      0.00        14

    accuracy                           0.14       279
   macro avg       0.01      0.02      0.01       279
weighted avg       0.03      0.14      0.04       279

d:\Python\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [95]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Assuming you have a DataFrame named 'data' with features and the target variable (label)
# X contains the features, and y contains the target variable

# Split the data into features (X) and target variable (y)
X = df.drop('CollegeName', axis=1)
y = df['CollegeName']

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the Support Vector Classifier
clf = SVC()

# Train the model using the training data
clf.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Accuracy: 0.12186379928315412
Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         2
          10       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         6
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         3
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         6
          19       0.00      0.00      0.00         5
          20       0.00      0.00      0.00         5
          21       0.00      0.00      0.00         5
          23       0.00      0.00      0.00        12
          24       0.00      0.00      0.00        16
          25       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         3
          28       0.00      0.00      0.00         6
          29       0.00      0.00      0.00         8
          30       0.13      0.74      0.22        35
          32       0.00      0.00      0.00         1
          34       0.00      0.00      0.00         2
          35       0.00      0.00      0.00         3
          36       0.00      0.00      0.00         7
          37       0.00      0.00      0.00         2
          41       0.00      0.00      0.00         2
          42       0.10      0.50      0.17        16
          43       0.00      0.00      0.00         2
          44       0.00      0.00      0.00         6
          45       0.00      0.00      0.00        10
          46       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         2
          52       0.00      0.00      0.00         3
          53       0.00      0.00      0.00         3
          55       0.00      0.00      0.00        10
          56       0.00      0.00      0.00         8
          57       0.00      0.00      0.00        12
          58       0.00      0.00      0.00         1
          60       0.00      0.00      0.00         1
          62       0.00      0.00      0.00         2
          63       0.00      0.00      0.00         3
          64       0.00      0.00      0.00         2
          66       0.00      0.00      0.00         4
          67       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         1
          69       0.00      0.00      0.00         3
          70       0.00      0.00      0.00         1
          72       0.00      0.00      0.00         3
          73       0.00      0.00      0.00         5
          74       0.00      0.00      0.00         3
          77       0.00      0.00      0.00         2
          81       0.00      0.00      0.00         1
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         1
          84       0.00      0.00      0.00         1
          85       0.00      0.00      0.00         1
          89       0.00      0.00      0.00         1
          90       0.00      0.00      0.00         1
          93       0.00      0.00      0.00         2
          94       0.00      0.00      0.00        14

    accuracy                           0.12       279
   macro avg       0.00      0.02      0.01       279
weighted avg       0.02      0.12      0.04       279

d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
d:\Python\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [96]:
df=pd.read_csv('BE_data.csv')

In [97]:
df

,CollegeName,Location,Course,Category,Rank,MerirMarks
0,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,DS,36000,0.000000
1,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EVS,18200,55.101835
2,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,EWS,18200,55.101835
3,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,Open,14510,64.015973
4,A.D.Patel Institute Of Technology,Karamsad,ARTIFICIAL INTELLIGENCE AND DATA SCIENCE,SC,36000,0.000000
...,...,...,...,...,...,...
5581,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,EWS,36000,0.000000
5582,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,Open,32209,16.951321
5583,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,SC,36000,0.000000
5584,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,SEBC,36000,0.000000
5585,Vishwakarma Government Engineering College,Ahmedabad,POWER ELECTRONICS,TFW,14812,63.235167

In [101]:
df.Course.unique()

array(['ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
       'AUTOMOBILE ENGINEERING', 'CIVIL ENGINEERING',
       'COMPUTER ENGINEERING', 'COMPUTER SCIENCE & DESIGN',
       'ELECTRICAL ENGINEERING',
       'ELECTRONICS & COMMUNICATION ENGINEERING',
       'FOOD PROCESSING TECHNOLOGY', 'INFORMATION TECHNOLOGY',
       'MECHANICAL ENGINEERING', 'CIVIL & INFRASTRUCTURE ENGINEERING',
       'COMPUTER SCIENCE & ENGINEERING (ARTIFICIAL IN',
       'INFORMATION & COMMUNICATION TECHNOLOGY',
       'AERONAUTICAL ENGINEERING', 'CHEMICAL ENGINEERING',
       'COMPUTER SCIENCE & BIOSCIENCES', 'COMPUTER SCIENCE & ENGINEERING',
       'COMPUTER ENGINEERING (SOFTWARE ENGINEERIN',
       'COMPUTER SCIENCE & ENGINEERING (CLOUD COMP',
       'AUTOMATION AND ROBOTICS', 'ENVIRONMENTAL ENGINEERING',
       'NANO TECHNOLOGY', 'PHARMACEUTICAL ENGINEERING',
       'ROBOTICS AND AUTOMATION', 'ELECTRONICS ENGINEERING',
       'PRODUCTION ENGINEERING', 'MANUFACTURING ENGINEERING',
       'PLASTIC ENGINEERING', 'CYBER SECURITY', 'MECHATRONICS',
       'BIOTECHNOLOGY', 'ELECTRICAL AND ELECTRONICS ENGINEERING',
       'HONS. IN ICT WITH MINOR IN COMPUTATIONAL SCI',
       'MATHEMATICS AND COMPUTING',
       'METALLURGICAL AND MATERIALS ENGINEERING', 'TEXTILE ENGINEERING',
       'TEXTILE PROCESSING', 'TEXTILE TECHNOLOGY', 'WATER MANAGEMENT ***',
       'INSTRUMENTATION & CONTROL ENGINEERING',
       'COMPUTER SCIENCE & ENGINEERING (IOT)',
       'COMPUTER SCIENCE & ENGINEERING (BIG DATA AN',
       'COMPUTER SCIENCE & ENGINEERING (CLOUD BASE',
       'COMPUTER SCIENCE & ENGINEERING (CYBER SECUR',
       'BIOMEDICAL ENGINEERING',
       'COMPUTER ENGINEERING (ARTIFICIAL INTELLIGENC',
       'COMPUTER SCIENCE & BUSINESS SYSTEMS', 'MARINE ENGINEERING',
       'PETROCHEMICAL ENGINEERING', 'MINING ENGINEERING', 'METALLURGY',
       'METALLURGICAL ENGINEERING',
       'ELECTRONICS & INSTRUMENTATION ENGINEERING',
       'COMPUTER SCIENCE & ENGINEERING (DATA SCIENC',
       'CIVIL ENGINEERING (Construction Engg. & Managem',
       'COMPUTER ENGINEERING (Cloud Tech. & Info.Sec.)',
       'COMPUTER ENGINEERING (Data Science)',
       'MECHANICAL ENGINEERING (CAD & ADV. CNC.)',
       'MECHATRONICS (IND. AUTOMATION & ROBOTICS)',
       'ELECTRONICS & COMMUNICATION (Communication', 'PLASTIC TECHNOLOGY',
       'RUBBER TECHNOLOGY', 'INDUSTRIAL ENGINEERING', 'POWER ELECTRONICS',
       'ARTIFICIAL INTELLIGENCE(AI) AND MACHINE LEARNI',
       'ROBOTICS & ARTIFICIAL INTELLIGENCE',
       'COMPUTER ENGINEERING (MACHINE LEARNING & A',
       'INFORMATION TECHNOLOGY & ENGINEERING', 'PETROLEUM ENGINEERING',
       'AIRCRAFT MAINTENANCE ENGINEERING',
       'COMPUTER SCIENCE & ENGINEERING (BLOCK CHAIN',
       'COMPUTER SCIENCE & ENGINEERING (INTERNET OF',
       'COMPUTER SCIENCE & ENGINEERING (NETWORKS)',
       'COMPUTER SCIENCE & TECHNOLOGY', 'COMPUTER TECHNOLOGY',
       'INFORMATION TECHNOLOGY (ARTIFICIAL INTELLIGE',
       'INFORMATION TECHNOLOGY (CYBER SECURITY)',
       'AGRICULTURAL ENGINEERING', 'DAIRY TECHNOLOGY',
       'FIRE & SAFETY ENGINEERING', 'FOOD TECHNOLOGY',
       'CHEMICAL & BIOCHEMICAL ENGINEERING',
       'FIRE AND ENVIRONMENT HEALTH SAFETY ENGINEER',
       'CHEMICAL ENGINEERING (GREEN TECHNOLOGY AND',
       'CHEMICAL TECHNOLOGY', 'ENVIRONMENTAL SCIENCE & TECHNOLOGY',
       'COMPUTER ENGINEERING (CLOUD COMPUTING)',
       'ARTIFICIAL INTELLIGENCE', 'CLOUD TECH &INFORMATION SECURITY',
       'ENVIRONMENT ENGINEERING', 'MOBILE APPLICATION & CLOUD TECHOLOGY'],
      dtype=object)

In [105]:
from q_model import pre_quest
print(pre_quest('How to register for ACPDC or Diploma courses?'))

2